// <auto-generated />
namespace ArtistsMVCDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SeedTheImagesOfAlbums : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedTheImagesOfAlbums));
        
        string IMigrationMetadata.Id
        {
            get { return "202201120922023_SeedTheImagesOfAlbums"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
